version: "3.1"

services:

  postgres_kafka_config:
    container_name: postgres_kafka_config
    healthcheck:
      test: "pg_isready -h localhost -p 5432 -q -U postgres"
      interval: 3s
      timeout: 5s
      retries: 5
    image: postgres:10.4-alpine
    environment:
      POSTGRES_DB: kafka_config
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - /var/lib/postgresql/data/
    restart: always

  kafka_config:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: bash /code/docker-entrypoint-dev.sh
    container_name: kafka_config
    image: kafka_config
    volumes:
      - .:/code
    ports:
      - "8080:8080"
    depends_on:
      - postgres_kafka_config
    environment:
      ALLOWED_HOSTS: localhost,127.0.0.1,0.0.0.0
      CORS_ORIGIN_WHITELIST: localhost,127.0.0.1,0.0.0.0
      DATABASE_ENGINE: "postgresql"
      DATABASE_NAME: "kafka_config"
      DATABASE_USER: "root"
      DATABASE_PASSWORD: "root"
      DATABASE_HOST: "postgres_kafka_config"
      DATABASE_PORT: "5432"
      DEBUG: "True"
      SECRET_KEY: "nothing"
      JWT_PUBLIC_KEY_RSA_BUILDLY: |-
        -----BEGIN PUBLIC KEY-----
        MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBALFc9NFZaOaSwUMPNektbtJqEjYZ6IRB
        qhqvJu1hKPYn9HYd75c0gIDYHJ9lb7QwQvg44aO27104rDK0xSstzL0CAwEAAQ==
        -----END PUBLIC KEY-----
      STATIC_ROOT: /static/
